name: Build and Push Docker Image

on: [push]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Previous tag
        id: previous_tag
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker Image Tag
        id: set_docker_tag
        run: echo "DOCKER_IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/fund-o-api-server:${{ steps.previous_tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Build Docker Image and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAG }}
          platforms: |
            linux/amd64
            linux/arm64
